name: Atualiza Feed Dinamize

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 * * * *' # roda a cada hora; ajuste se quiser (UTC)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Run transform script
        run: node transform.js

      - name: Commit transformed feed (if changed)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/feed-dinamize.xml || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Atualiza feed transformado [ci]" && git push
          fi
